// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: restaurantuserservicerpb/userservice.proto

package restaurantuserservicerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num1          int32                  `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2          int32                  `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_restaurantuserservicerpb_userservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantuserservicerpb_userservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_restaurantuserservicerpb_userservice_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *SumRequest) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type SumReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumReponse) Reset() {
	*x = SumReponse{}
	mi := &file_restaurantuserservicerpb_userservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumReponse) ProtoMessage() {}

func (x *SumReponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantuserservicerpb_userservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumReponse.ProtoReflect.Descriptor instead.
func (*SumReponse) Descriptor() ([]byte, []int) {
	return file_restaurantuserservicerpb_userservice_proto_rawDescGZIP(), []int{1}
}

func (x *SumReponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_restaurantuserservicerpb_userservice_proto protoreflect.FileDescriptor

const file_restaurantuserservicerpb_userservice_proto_rawDesc = "" +
	"\n" +
	"*restaurantuserservicerpb/userservice.proto\x12\x15restaurantuserservice\"4\n" +
	"\n" +
	"SumRequest\x12\x12\n" +
	"\x04num1\x18\x01 \x01(\x05R\x04num1\x12\x12\n" +
	"\x04num2\x18\x02 \x01(\x05R\x04num2\"$\n" +
	"\n" +
	"SumReponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2f\n" +
	"\x15RestaurantUserService\x12M\n" +
	"\x03Sum\x12!.restaurantuserservice.SumRequest\x1a!.restaurantuserservice.SumReponse\"\x00B0Z.RestaurantUserService/restaurantuserservicerpbb\x06proto3"

var (
	file_restaurantuserservicerpb_userservice_proto_rawDescOnce sync.Once
	file_restaurantuserservicerpb_userservice_proto_rawDescData []byte
)

func file_restaurantuserservicerpb_userservice_proto_rawDescGZIP() []byte {
	file_restaurantuserservicerpb_userservice_proto_rawDescOnce.Do(func() {
		file_restaurantuserservicerpb_userservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurantuserservicerpb_userservice_proto_rawDesc), len(file_restaurantuserservicerpb_userservice_proto_rawDesc)))
	})
	return file_restaurantuserservicerpb_userservice_proto_rawDescData
}

var file_restaurantuserservicerpb_userservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_restaurantuserservicerpb_userservice_proto_goTypes = []any{
	(*SumRequest)(nil), // 0: restaurantuserservice.SumRequest
	(*SumReponse)(nil), // 1: restaurantuserservice.SumReponse
}
var file_restaurantuserservicerpb_userservice_proto_depIdxs = []int32{
	0, // 0: restaurantuserservice.RestaurantUserService.Sum:input_type -> restaurantuserservice.SumRequest
	1, // 1: restaurantuserservice.RestaurantUserService.Sum:output_type -> restaurantuserservice.SumReponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_restaurantuserservicerpb_userservice_proto_init() }
func file_restaurantuserservicerpb_userservice_proto_init() {
	if File_restaurantuserservicerpb_userservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurantuserservicerpb_userservice_proto_rawDesc), len(file_restaurantuserservicerpb_userservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurantuserservicerpb_userservice_proto_goTypes,
		DependencyIndexes: file_restaurantuserservicerpb_userservice_proto_depIdxs,
		MessageInfos:      file_restaurantuserservicerpb_userservice_proto_msgTypes,
	}.Build()
	File_restaurantuserservicerpb_userservice_proto = out.File
	file_restaurantuserservicerpb_userservice_proto_goTypes = nil
	file_restaurantuserservicerpb_userservice_proto_depIdxs = nil
}
