// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: restaurantuserservicerpb/userservice.proto

package restaurantuserservicerpb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// RestaurantUserServiceClient is the client API for RestaurantUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantUserServiceClient interface {
}

type restaurantUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantUserServiceClient(cc grpc.ClientConnInterface) RestaurantUserServiceClient {
	return &restaurantUserServiceClient{cc}
}

// RestaurantUserServiceServer is the server API for RestaurantUserService service.
// All implementations must embed UnimplementedRestaurantUserServiceServer
// for forward compatibility.
type RestaurantUserServiceServer interface {
	mustEmbedUnimplementedRestaurantUserServiceServer()
}

// UnimplementedRestaurantUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestaurantUserServiceServer struct{}

func (UnimplementedRestaurantUserServiceServer) mustEmbedUnimplementedRestaurantUserServiceServer() {}
func (UnimplementedRestaurantUserServiceServer) testEmbeddedByValue()                               {}

// UnsafeRestaurantUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantUserServiceServer will
// result in compilation errors.
type UnsafeRestaurantUserServiceServer interface {
	mustEmbedUnimplementedRestaurantUserServiceServer()
}

func RegisterRestaurantUserServiceServer(s grpc.ServiceRegistrar, srv RestaurantUserServiceServer) {
	// If the following call pancis, it indicates UnimplementedRestaurantUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RestaurantUserService_ServiceDesc, srv)
}

// RestaurantUserService_ServiceDesc is the grpc.ServiceDesc for RestaurantUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restaurantuserservice.RestaurantUserService",
	HandlerType: (*RestaurantUserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "restaurantuserservicerpb/userservice.proto",
}
